#lang racket
(struct student (name id dorm))
(define freshman1 (student 'kevin 1234 'Newhall))
(set! freshman1 (student 'Alex 4567 'Shenzhen))
(define mimi (student 'Mimi 1234 'NewHall))
(define nicole (student 'Nicole 5678 'NewHall))
(define rose (student 'Rose 8765 'NewHall))
(define eric (student 'Eric 4321 'NewHall))
(define in-class (list mimi nicole rose eric))
(student-id (third in-class))
(struct student-body (freshmen sophomores juniors seniors))
(define all-students
  (student-body (list freshman1 (student 'Mary 0101 'OldHall))
                (list (student 'Jeff 5678 'OldHall))
                (list (student 'Bob 4321 'Apartment))
                empty))
(student-name (first (student-body-freshmen all-students)))
(student? freshman1)